"""Trading domain objects - Portfolio State, Decisions, Blueprints, Positions, Trades."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any
import math
import time

@dataclass(frozen=True)
class PortfolioState:
    """Portfolio state snapshot for decision making."""
    total_equity: float = 10000.0
    available_capital: float = 10000.0
    total_exposure: float = 0.0
    open_positions_count: int = 0
    risk_budget: float = 3.0
    risk_budget_used: float = 0.0
    portfolio_heat: float = 0.0
    drawdown: float = 0.0
    health_score: float = 1.0

    def __post_init__(self) -> None:
        for val in [self.total_equity, self.available_capital, self.total_exposure, 
                    self.risk_budget, self.risk_budget_used, self.drawdown]:
            if math.isnan(val) or math.isinf(val):
                raise ValueError(f"PortfolioState contains NaN or Inf: {val}")
        if self.total_equity < 0:
            raise ValueError("Total equity cannot be negative")

@dataclass(frozen=True)
class Decision:
    """Final decision contract."""
    decision_type: str
    direction: str
    confidence: float = 0.0
    utility: float = 0.0
    priority: int = 0
    reasoning: tuple[str, ...] = field(default_factory=tuple)
    evidence_summary: dict[str, float] = field(default_factory=dict)
    risk_summary: dict[str, float] = field(default_factory=dict)
    portfolio_impact: dict[str, float] = field(default_factory=dict)
    trace_id: str = ""
    timestamp: float = 0.0

    def __post_init__(self) -> None:
        if self.decision_type not in ('TRADE', 'NO_TRADE', 'WAIT', 'SCALE_IN', 'SCALE_OUT', 'EXIT'):
            raise ValueError(f"Invalid decision type: {self.decision_type}")
        if self.direction not in ('LONG', 'SHORT', 'FLAT'):
            raise ValueError(f"Invalid direction: {self.direction}")
        if math.isnan(self.confidence) or not (0.0 <= self.confidence <= 1.0):
            raise ValueError(f"Decision confidence out of bounds: {self.confidence}")

@dataclass(frozen=True)
class TradeBlueprint:
    """Complete trade execution plan generated by Risk Optimizer."""
    decision_id: str
    symbol: str
    exchange: str
    direction: str
    probability: float
    confidence: float
    expected_value: float
    position_size: float
    risk_size: float
    entry_price: float
    stop_loss: float
    take_profit: float
    tp1: float
    tp2: float
    tp3: float
    leverage: float = 1.0
    stop_model: str = "structure_hybrid"
    trade_quality_index: float = 0.0
    risk_reward_ratio: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        for val in [self.position_size, self.risk_size, self.entry_price, self.stop_loss, self.take_profit]:
            if math.isnan(val) or math.isinf(val):
                raise ValueError(f"TradeBlueprint contains NaN or Inf: {val}")
        if self.position_size < 0:
            raise ValueError("Position size cannot be negative")

@dataclass
class Position:
    """Open position - mutable living entity."""
    position_id: str
    blueprint_id: str
    symbol: str
    exchange: str
    direction: str
    entry_price: float
    quantity: float
    stop_loss: float
    take_profit: float
    entry_time: float = field(default_factory=time.time)
    current_price: float = 0.0
    floating_pnl: float = 0.0
    realized_pnl: float = 0.0
    max_adverse_excursion: float = 0.0
    max_favorable_excursion: float = 0.0
    status: str = "OPEN"
    exit_price: float = 0.0
    exit_time: float = 0.0

    def __post_init__(self) -> None:
        for val in [self.entry_price, self.quantity, self.stop_loss, self.take_profit]:
            if math.isnan(val) or math.isinf(val):
                raise ValueError(f"Position contains NaN or Inf: {val}")
        if self.entry_price <= 0 or self.quantity <= 0:
            raise ValueError("Entry price and quantity must be positive")
        if self.direction not in ('LONG', 'SHORT'):
            raise ValueError(f"Invalid direction: {self.direction}")

    def update_market_price(self, current_price: float) -> None:
        if math.isnan(current_price) or math.isinf(current_price) or current_price <= 0:
            return
        self.current_price = current_price
        if self.direction == "LONG":
            self.floating_pnl = (current_price - self.entry_price) * self.quantity
            self.max_favorable_excursion = max(self.max_favorable_excursion, current_price - self.entry_price)
            self.max_adverse_excursion = min(self.max_adverse_excursion, current_price - self.entry_price)
        else:
            self.floating_pnl = (self.entry_price - current_price) * self.quantity
            self.max_favorable_excursion = max(self.max_favorable_excursion, self.entry_price - current_price)
            self.max_adverse_excursion = min(self.max_adverse_excursion, self.entry_price - current_price)

    def close(self, exit_price: float, exit_time: float) -> 'Trade':
        if self.status != "OPEN":
            raise ValueError(f"Cannot close position {self.position_id} with status {self.status}")
        if self.direction == "LONG":
            self.realized_pnl = (exit_price - self.entry_price) * self.quantity
        else:
            self.realized_pnl = (self.entry_price - exit_price) * self.quantity
        self.floating_pnl = 0.0
        self.exit_price = exit_price
        self.exit_time = exit_time
        self.status = "CLOSED"
        
        # Correct R-Multiple Calculation: Total PnL / Total Risk Amount
        risk_pts = abs(self.entry_price - self.stop_loss) if self.stop_loss > 0 else 1.0
        total_risk_amount = risk_pts * self.quantity
        r_multiple = self.realized_pnl / total_risk_amount if total_risk_amount > 0 else 0.0
        
        return Trade(
            trade_id=f"TRADE_{self.position_id}", position_id=self.position_id, symbol=self.symbol,
            direction=self.direction, entry_price=self.entry_price, exit_price=exit_price,
            quantity=self.quantity, pnl=self.realized_pnl, r_multiple=r_multiple, win=self.realized_pnl > 0
        )

@dataclass(frozen=True)
class Trade:
    """Closed trade record. Immutable."""
    trade_id: str
    position_id: str
    symbol: str
    direction: str
    entry_price: float
    exit_price: float
    quantity: float
    pnl: float
    r_multiple: float
    win: bool
    timestamp: float = field(default_factory=time.time)
